# Generated by Django 4.2.16 on 2026-03-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('query_type', models.CharField(choices=[('qa', 'Q&A'), ('recommendation', 'Recommendation'), ('portfolio_action', 'Portfolio Action'), ('forecast', 'Forecast'), ('sentiment', 'Sentiment')], default='qa', max_length=20)),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_type', models.CharField(blank=True, max_length=50, null=True)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
