# Generated by Django 4.2.16 on 2026-03-23 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(db_index=True, default='Unknown', max_length=100)),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('change_percent', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('price_52w_high', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('price_52w_low', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_price_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='stocks_stoc_symbol_3e1bfd_idx'), models.Index(fields=['sector'], name='stocks_stoc_sector_6c2055_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_sentiment', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('label', models.CharField(choices=[('bullish', 'Bullish'), ('neutral', 'Neutral'), ('bearish', 'Bearish')], default='neutral', max_length=10)),
                ('news_sentiment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('analyst_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sample_size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('linear', 'Linear Regression'), ('arima', 'ARIMA'), ('lstm', 'LSTM Neural Network')], max_length=20)),
                ('forecast_days', models.IntegerField(choices=[(7, '7 Days'), (30, '1 Month'), (365, '1 Year')])),
                ('predicted_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('confidence_upper', models.DecimalField(decimal_places=4, max_digits=14)),
                ('confidence_lower', models.DecimalField(decimal_places=4, max_digits=14)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('stock', 'model_type', 'forecast_days')},
            },
        ),
    ]
