# Generated by Django 4.2.16 on 2026-03-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='change_7d_percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ml_rnn_signal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='ml_sparkline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='quote_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
