# Generated by Django 4.2.16 on 2026-03-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_ml_universe_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='universe',
            field=models.CharField(db_index=True, default='IN', max_length=2),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['universe'], name='stocks_stoc_univers_ddaa6d_idx'),
        ),
    ]
