# Generated by Django 4.2.16 on 2026-03-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('purchase_date', models.DateField()),
                ('current_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('gain_loss', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('gain_loss_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('invested_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_invested', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_gain_loss', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_return_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
